<a href="https://colab.research.google.com/github/rahiakela/mathematics-for-machine-learning/blob/main/mathematics-for-machine-learning-and-data-science-specialization/01-learning-linear-algebra/week1-system-of-linear-equations/02_solving_linear_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Solving Linear Systems: 2 variables

By completing this lab, you will be able to use basic programming skills with Python and `NumPy` package to solve systems of linear equations. In this notebook you will:

- Use `NumPy` linear algebra package to find the solutions of the system of linear equations
- Find the solution for the system of linear equations using elimination method
- Evaluate the determinant of the matrix and examine the relationship between matrix singularity and number of solutions of the linear system

**Table of Contents**

- [ 1 - Representing and Solving System of Linear Equations using Matrices](#1)
  - [ 1.1 - System of Linear Equations](#1.1)
  - [ 1.2 - Solving Systems of Linear Equations using Matrices](#1.2)
  - [ 1.3 - Evaluating Determinant of a Matrix](#1.3)
- [ 2 - Solving System of Linear Equations using Elimination Method](#2)
  - [ 2.1 - Elimination Method](#2.1)
  - [ 2.2 - Preparation for the Implementation of Elimination Method in the Code](#2.2)
  - [ 2.3 - Implementation of Elimination Method](#2.3)
  - [ 2.4 - Graphical Representation of the Solution](#2.4)
- [ 3 - System of Linear Equations with No Solutions](#3)
- [ 4 - System of Linear Equations with Infinite Number of Solutions](#4)

##Setup

In [3]:
import numpy as np

import matplotlib.pyplot as plt

<a name='1'></a>
## 1 - Representing and Solving System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - System of Linear Equations

A **system of linear equations** (or **linear system**) is a collection of one or more linear equations involving the same variables. For example:


$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}\tag{1}$$

is a system of two equations with two unknown variables $x_1$, $x_2$. **To solve** a system of linear equations means to find such values of the variables $x_1$, $x_2$, that all of its equations are simultaneously satisfied.

A linear system is **inconsistent** if it has no solution, and otherwise it is said to be **consistent**. Consistent system can have one or infinite number of solutions.

<a name='1.2'></a>
### 1.2 - Solving Systems of Linear Equations using Matrices

Linear systems with two equations are easy to solve manually, but preparing for more complicated cases, you will investigate some solution techniques. 

`NumPy` linear algebra package provides quick and reliable way to solve the system of linear equations using function `np.linalg.solve(A, b)`. 

Here $A$ is a matrix, each row of which represents one equation in the system and each column corresponds to the variable $x_1$, $x_2$. And $b$ is a 1-D array of the free (right side) coefficients. More information about the `np.linalg.solve()` function can be found in [documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html).

Given the system of linear equations $(1)$, you can set matrix $A$ and 1-D array $b$ as:

In [4]:
A = np.array([
  [-1, 3],
  [3, 2]
], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print(f"Matrix A: \n{A}")
print(f"Array b: \n{b}")

Matrix A: 
[[-1.  3.]
 [ 3.  2.]]
Array b: 
[7. 1.]


Check the dimensions of $A$ and $b$ using the `shape` attribute (you can also use `np.shape()` as an alternative):

In [5]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

# print(f"Shape of A: {np.shape(A)}")
# print(f"Shape of A: {np.shape(b)}")

Shape of A: (2, 2)
Shape of b: (2,)


Now simply use `np.linalg.solve(A, b)` function to find the solution of the system $(1)$. The result will be saved in the 1-D array $x$. The elements will correspond to the values of $x_1$ and $x_2$:

In [6]:
x = np.linalg.solve(A, b)
print(f"Solution: {x}")

Solution: [-1.  2.]


Try to substitute those values of $x_1$ and $x_2$ into the original system of equations to check its consistency.

In [7]:
e1 = (-1 * -1) + 3 * 2 - 7
print(f"e1: {e1}")

e1: 0


In [8]:
e2 = (3 * -1) + 2 * 2 - 1
print(f"e2: {e2}")

e2: 0


<a name='1.3'></a>
### 1.3 - Evaluating Determinant of a Matrix

Matrix $A$ corresponding to the linear system $(1)$ is a **square matrix** - it has the same number of rows and columns. In case of a square matrix it is possible to calculate its determinant - a real number which characterizes some properties of the matrix. Linear system containing two (or more) equations with the same number of unknown variables will have one solution if and only if matrix $A$ has non-zero determinant.

Let's calculate the determinant using `NumPy` linear algebra package. You can do it with the `np.linalg.det(A)` function. More information about it can be found in [documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html).

In [9]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


Note that its value is non-zero, as expected for a system with exactly one solution.

<a name='2'></a>
## 2 - Solving System of Linear Equations using Elimination Method

You can see how easy it is to use contemporary packages to solve linear equations. However, for deeper understanding of mathematical concepts, it is important to practice some solution techniques manually. Programming approach can still help here to reduce the amount of arithmetical calculations, and focus on the method itself.

<a name='2.1'></a>
### 2.1 - Elimination Method

In the **elimination method** you either add or subtract the equations of the linear system to get an equation with smaller number of variables. If needed, you can also multiply whole equation by non-zero number. 

Take a look at the system $(1)$ again:

$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}$$

Multiply first equation by 3, add it to the second equation and exchange the second equation with the result of this addition:

$$\begin{cases} 
-x_1+3x_2=7, \\ 11x_2=22. \end{cases}\tag{2}$$

You eliminated variable $x_1$ from the second equation and brough it to the form where, dividing by $11$, you can see the solution value for $x_2$: $x_2=2$. Now take $x_2=2$ in the first equation:

$$\begin{cases} 
-x_1+3 \times 2=7, \\ x_2=2, \end{cases}\tag{3}$$

And find the solution:

$$\begin{cases} 
x_1=-1, \\ x_2=2. \end{cases}\tag{4}$$

Check that it's the same one that you found in the section [1.2](#1.2).

<a name='2.2'></a>
### 2.2 - Preparation for the Implementation of Elimination Method in the Code

Representing the system in a matrix form as
$\begin{bmatrix}
-1 & 3 & 7 \\
3 & 2 & 1
\end{bmatrix},
$
you can apply the same operations to the rows of the matrix with Python code.

Unify matrix $A$ and array $b$ into one matrix using `np.hstack()` function. 

Note that the shape of the originally defined array $b$ was $(2,)$, to stack it with the $(2, 2)$ matrix you need to use `.reshape((2, 1))` function:

In [14]:
print(A)

[[-1.  3.]
 [ 3.  2.]]


In [15]:
print(b)

[7. 1.]


In [10]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


Let's review how to extract a row of a matrix, which will help later to perform required operations with the rows. 

Remember, that indexing of arrays in Python starts from zero, so to extract second row of a matrix, you need to use the following code:

In [11]:
print(A_system[1])

[3. 2. 1.]


In [12]:
print(A_system[0])

[-1.  3.  7.]


<a name='2.3'></a>
### 2.3 - Implementation of Elimination Method

Let's apply some operations to the matrix $A\_system$ to eliminate variable . First, copy the matrix to keep the original one without any changes. Then multiply first row by 3, add it to the second row and exchange the second row with the result of this addition:

In [13]:
A_system_res = A_system.copy()

A_system_res[1] = 3 * A_system_res[0] + A_system_res[1]
print(A_system_res)

[[-1.  3.  7.]
 [ 0. 11. 22.]]


Multipy second row by $1/11$:

In [16]:
A_system_res[1] = 1 / 11 * A_system_res[1]
print(A_system_res)

[[-1.  3.  7.]
 [ 0.  1.  2.]]


<a name='2.4'></a>
### 2.4 - Graphical Representation of the Solution

A linear equation in two variables (here, $x_1$ and $x_2$) is represented geometrically by a line which points $(x_1, x_2)$ make up the collection of solutions of the equation. This is called the **graph of the linear equation**. In case of the system of two equations there will be two lines corresponding to each of the equations, and the solution will be the intersection point of those lines.

In the following code you will define a function `plot_lines()` to plot the lines and use it later to represent the solution which you found earlier. Do not worry if the code in the following cell will not be clear - at this stage this is not important code to understand.